apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: my-container
        minAllowed:
          memory: 500Mi
          cpu: 500m
        maxAllowed:
          memory: 2Gi
          cpu: 2
        controlledResources: ["memory", "cpu"]
