name: Update VPA and Apply to Minikube
run-name: Update VPA and Apply to Minikube

on:
  push:
    branches:
      - vpa-gha
env:
  MIN_CPU: 250m
  MAX_CPU: 1
  MIN_MEMORY: 250Mi
  MAX_MEMORY: 1Gi

jobs:
  update-vpa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      # - name: Install kubectl
      #   run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y kubectl

      # - name: Set up Minikube
      #   run: |
      #     curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
      #     chmod +x minikube
      #     sudo mv minikube /usr/local/bin/

      #     minikube start --driver=none

      - name: Update Vertical Pod Autoscaler YAML
        run: |
          export MIN_CPU=250m
          export MAX_CPU=1
          export MIN_MEMORY=250Mi
          export MAX_MEMORY=1Gi
          echo $MIN_CPU
          python3 update_vpa.py
          # sed -i "s|memory: 500Mi|memory: $MIN_MEMORY|g" vpa.yml
          # sed -i "s|cpu: 500m|cpu: $MIN_CPU|g" vpa.yml
          # sed -i "s|memory: 2Gi|memory: $MAX_MEMORY|g" vpa.yml
          # sed -i "s|cpu: 2|cpu: $MAX_CPU|g" vpa.yml
          cat vpa.yml


      # - name: Apply VPA to Minikube
      #   run: |
      #     kubectl apply -f vpa.yml
      - name: Configure Git
        run: |
          git config --local user.email "git_bot@example.com"
          git config --local user.name "git_bot"
          
      - name: Write invertory file to repo
        run: |
            ls -a
            if git diff --quiet -- vpa.yml; then
            echo "No changes to vpa.yml."
            else
            git add vpa.yml
            git commit -m "Update VPA"
            git push
            fi            
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
